---
- name: install postgresql12
  hosts: log
  become: yes

  tasks:
  - name: install postgresql  
    apt: name=postgresql12-server state=latest	
  - name: start service
    service: name=postgresql12-server state=started enabled=yes	
