---
- hosts: web
  become: yes
  tasks:
  -  name: Install zabbix agent
     become: yes
     apt:
        name: zabbix-agent
        state: present
        update_cache: yes
  - name: Stop service zabbix-agent
    become: yes
    service:
           name: zabbix-agent
           state: stopped

  - name: Remove zabbix config file
    become: yes
    file:
        path: /etc/zabbix/zabbix_agentd.conf
        state: absent

  - name: Create new zabbix config file from template
    become: yes
    template:
            src: "/etc/ansible/common/files/zabbix_agentd.conf"
            dest: "/etc/zabbix/zabbix_agentd.conf"

  - name: Start and enable service zabbix-agent
    become: yes
    service:
            name: zabbix-agent
            state: started
            enabled: yes
