---
- name: install Zabbix-agent
  hosts: web, log
  become: yes

  tasks:
  - name: ckeck linux version
    debug: var=ansible_distribution
  
  - name: install  Zabbix-agent ubuntu   
    apt: name=zabbix-agent  state=latest
    when: ansible_distribution == "Ubuntu"    
  - name: install  Zabbix-agent ubuntu
    yum: name=zabbix-agent  state=latest
    when: ansible_distribution == "CentOS"    
  - name: start service
    service: name=zabbix-agent state=started enabled=yes

